### ISSUE TITLE
availability of the code

### ISSUE THREAD

**Issue by thegodone** [chao1224/n_gram_graph#1]
Dear Shengchao Liu,

When do you will put the code online ?

In the paper you mention soon, when do you mean by that ?

thanks in advance,

BR

Guillaume

**Comment by chao1224** [comment]
Hi @thegodone 

The code has not been published yet because we are adding more datasets and baseline methods.

If you are referring to the arxiv or the NeurIPS workshop (MLMM) version, we have made a lot of updates recently, including the `n-gram` representation method. And we will publish both the code and paper when they are ready.

**Comment by maxentile** [comment]
Hi!

Very interesting work. I am also interested in the reference implementation, which [this NeurIPS paper](https://papers.nips.cc/paper/9054-n-gram-graph-simple-unsupervised-representation-for-graphs-with-applications-to-molecules) mentions is available here.

Thanks in advance,
Josh

**Comment by Dinxin** [comment]
Hi, I am very interested in your work and curious about the implementation. So when would you release your code? I remember that you mentioned in your NeurlPS 2019 paper that your code is available here?

**Comment by mehmetfdemirel** [comment]
Hi @Dinxin and @maxentile,

Thank you for your interest in our paper! We will be publishing the code by next week.

Mehmet

**Comment by Dinxin** [comment]
Next week ?

**Comment by chao1224** [comment]
@Dinxin 
In case you need it, the code is in the `init` branch, but not finalized yet.
Unfortunately, the server is dead this week. Once it's back, we will do the final test before merging.

**Comment by Dinxin** [comment]
@chao1224 Thank you! I will go to 'init' branch.

**Comment by sethglazier** [comment]
@chao1224 there appears to be a graph_util file that is not in the 'init' branch that many of the prepare_dataset files attempt to import.

**Comment by chao1224** [comment]
@sethglazier 
Thanks for poiting out. Please check the latest commit.

**Comment by chao1224** [comment]
@thegodone @maxentile @Dinxin @sethglazier 

Sorry for keep you guys waiting. The codes and the optimal hyperparameters are uploaded to the `init` branch! We will do some further clean-ups, like variable renaming. But you should be good to go now!
