### ISSUE TITLE
Error when appending loss

### ISSUE THREAD

**Issue by martinvoegele** [chao1224/n_gram_graph#4]
Hi, I've been trying to run an example of the code but when I execute test.sh in n_gram_graph/embedding, I get the following errors
```
Traceback (most recent call last):
  File "node_embedding.py", line 223, in <module>
    train()
  File "node_embedding.py", line 128, in train
    train_loss.append(loss.data[0])
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
Traceback (most recent call last):
  File "graph_embedding.py", line 150, in <module>
    model.load_state_dict(torch.load(weight_file))
  File "/home/martin/anaconda2/envs/n_gram_project/lib/python2.7/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: 'model_weight/delaney/0/50_CBoW_non_segment.pt'

```
Any help would be highly appreciated.

**Comment by chao1224** [comment]
Hi @martinvoegele 

The first issue is caused by the pytorch version.
In `gpu_env.yml` we are specifying using `pytorch=0.3.1`, and I guess you are using more recent version of pytorch. If that's the case, can you try replacing `loss.data[0]`with `loss.detach().item()`?

The second issue is because the graph-level embedding needs a pre-trained node-level embedding, so it should be OK if the previous one is fixed.

Feel free to let me know if you have any following-up questions.

**Comment by martinvoegele** [comment]
Indeed, it was the PyTorch version. 
Even though I installed the environment according to the instructions in this repo, anaconda installed pytorch 1.3.1 instead.
After making the change you suggest above, it works. Thanks a lot!

I get reasonable results for the test run
```
Pearson R2 on test set: 0.861874734124
R2 on test set: 0.857742890153
RMSE on test set: 0.804440138781
MAE on test set: 0.543774490603
```
However there is one warning:
```
n_gram_graph/n_gram_graph/model/random_forest_regression.py:36: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)
```
Can I ignore this one or is this a serious issue?

**Comment by chao1224** [comment]
@martinvoegele Gald it's working!

And yes, you can safely ignore it. Most `warnings` are not serious issues.

**Comment by martinvoegele** [comment]
Perfect, thanks!
